# workflow name
name: Release

# on events
on:
  #release:
  #  types:
  #      - created
  push:
  pull_request:


# workflow tasks
jobs:
  generate:
    permissions:
      contents: write
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install appindicator
        run: sudo apt-get install -y  gcc libgtk-3-dev libayatana-appindicator3-dev

      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
            platforms: 'linux/amd64, darwin/amd64, windows/amd64'
            #package: ''
            name: 'gohi'
            compress: 'true'
            dest: 'dist'


#      - name: Upload Windows Asset
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ github.event.release.upload_url }}
#          asset_path: ./dist/gohi-windows-amd64.tar.gz
#          asset_name: gohi-windows-amd64.tar.gz
#          asset_content_type: application/x-compressed-tar
